server:
  type: simple
  applicationConnectors:
    - type: http
      port: ${ALGORITHM_PORT:-8080}
      bindHost: 0.0.0.0

logging:
  level: ${LOG_LEVEL:-INFO}
  loggers:
    com: ${LOG_LEVEL:-DEBUG}
  appenders:
    - type: console
    - type: file
      currentLogFilename: ${LOG_DIR:-./logs}/algorithm.log
      archivedLogFilenamePattern: ${LOG_DIR:-./logs}/algorithm-%d{yyyy-MM-dd}.log.gz
      maxFileSize: 10MB
      archivedFileCount: 7
